spring:
   application:
      name: tesla-gateway
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/gateway?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
server:
   port: ${TESLA_SERVER_PORT:8089}
   metrcis: false
eureka:
   instance:
      prefer-ip-address: true
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
hazelcast:
   version: 1.0.0
management:
   metrics:
      export:
         influx:
            enabled: false
            uri: http://localhost:8086